[[actions]]
name = "play"
path = "view3dscene/view3dscene"

[[actions]]
name = "manual"
path = "https://castle-engine.io/view3dscene.php"

[[actions]]
name = "forums"
path = "https://castle-engine.io/talk.php"
